# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/life/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/life/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/life/Desktop/Library
  c:/Users/life/Desktop/packageA00/packageA00.srcs
  c:/Users/life/Desktop/package_A10/package_A10.srcs
  c:/Users/life/Desktop/packageA20/packageA20.srcs
  c:/Users/life/Desktop/packageA22/packageA22.srcs
  c:/Users/life/Desktop/packageA11/packageA11.srcs
  c:/Users/life/Desktop/packageA01/packageA01.srcs
  c:/Users/life/Desktop/project_debouncer/project_debouncer.srcs
  c:/Users/life/Desktop/project_A21_yeni/project_A21_yeni.srcs
} [current_project]
set_property ip_output_repo c:/Users/life/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/life/project_1/project_1.srcs/sources_1/imports/hdl/design_main_project_wrapper.v
add_files C:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/design_main_project.bd
set_property used_in_implementation false [get_files -all c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_debouncer_wrapper_0_0/bd/design_debouncer/design_debouncer_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_debouncer_wrapper_0_1/bd/design_debouncer/design_debouncer_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_debouncer_wrapper_0_2/bd/design_debouncer/design_debouncer_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A00_wrapper_0_0/bd/design_A00/design_A00_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A10_wrapper_0_1/bd/design_A10/design_A10_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A20_wrapper_0_0/bd/design_A20/design_A20_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A22_wrapper_0_0/bd/design_A22/design_A22_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/design_A11_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A01_wrapper_0_0/bd/design_A01/design_A01_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/design_yeni_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/design_main_project_ooc.xdc]
set_property is_locked true [get_files C:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/design_main_project.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/life/Desktop/Basys-3-Master.xdc
set_property used_in_implementation false [get_files C:/Users/life/Desktop/Basys-3-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_main_project_wrapper -part xc7a35tcpg236-1


write_checkpoint -force -noxdef design_main_project_wrapper.dcp

catch { report_utilization -file design_main_project_wrapper_utilization_synth.rpt -pb design_main_project_wrapper_utilization_synth.pb }
