# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/life/Desktop/Basys-3-Master.xdc

# Block Designs: bd/design_main_project/design_main_project.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project || ORIG_REF_NAME==design_main_project}]

# IP: bd/design_main_project/ip/design_main_project_design_debouncer_wrapper_0_0/design_main_project_design_debouncer_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_design_debouncer_wrapper_0_0 || ORIG_REF_NAME==design_main_project_design_debouncer_wrapper_0_0}]

# IP: bd/design_main_project/ip/design_main_project_design_debouncer_wrapper_0_1/design_main_project_design_debouncer_wrapper_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_design_debouncer_wrapper_0_1 || ORIG_REF_NAME==design_main_project_design_debouncer_wrapper_0_1}]

# IP: bd/design_main_project/ip/design_main_project_design_debouncer_wrapper_0_2/design_main_project_design_debouncer_wrapper_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_design_debouncer_wrapper_0_2 || ORIG_REF_NAME==design_main_project_design_debouncer_wrapper_0_2}]

# IP: bd/design_main_project/ip/design_main_project_xup_clk_divider_0_0/design_main_project_xup_clk_divider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xup_clk_divider_0_0 || ORIG_REF_NAME==design_main_project_xup_clk_divider_0_0}]

# IP: bd/design_main_project/ip/design_main_project_xup_dff_en_reset_0_0/design_main_project_xup_dff_en_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xup_dff_en_reset_0_0 || ORIG_REF_NAME==design_main_project_xup_dff_en_reset_0_0}]

# IP: bd/design_main_project/ip/design_main_project_dff_A00_0/design_main_project_dff_A00_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_dff_A00_0 || ORIG_REF_NAME==design_main_project_dff_A00_0}]

# IP: bd/design_main_project/ip/design_main_project_dff_A10_0/design_main_project_dff_A10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_dff_A10_0 || ORIG_REF_NAME==design_main_project_dff_A10_0}]

# IP: bd/design_main_project/ip/design_main_project_dff_A20_0/design_main_project_dff_A20_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_dff_A20_0 || ORIG_REF_NAME==design_main_project_dff_A20_0}]

# IP: bd/design_main_project/ip/design_main_project_dff_A20_1/design_main_project_dff_A20_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_dff_A20_1 || ORIG_REF_NAME==design_main_project_dff_A20_1}]

# IP: bd/design_main_project/ip/design_main_project_dff_A20_2/design_main_project_dff_A20_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_dff_A20_2 || ORIG_REF_NAME==design_main_project_dff_A20_2}]

# IP: bd/design_main_project/ip/design_main_project_dff_A20_3/design_main_project_dff_A20_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_dff_A20_3 || ORIG_REF_NAME==design_main_project_dff_A20_3}]

# IP: bd/design_main_project/ip/design_main_project_design_A00_wrapper_0_0/design_main_project_design_A00_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_design_A00_wrapper_0_0 || ORIG_REF_NAME==design_main_project_design_A00_wrapper_0_0}]

# IP: bd/design_main_project/ip/design_main_project_design_A10_wrapper_0_1/design_main_project_design_A10_wrapper_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_design_A10_wrapper_0_1 || ORIG_REF_NAME==design_main_project_design_A10_wrapper_0_1}]

# IP: bd/design_main_project/ip/design_main_project_design_A20_wrapper_0_0/design_main_project_design_A20_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_design_A20_wrapper_0_0 || ORIG_REF_NAME==design_main_project_design_A20_wrapper_0_0}]

# IP: bd/design_main_project/ip/design_main_project_design_A22_wrapper_0_0/design_main_project_design_A22_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_design_A22_wrapper_0_0 || ORIG_REF_NAME==design_main_project_design_A22_wrapper_0_0}]

# IP: bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/design_main_project_design_A11_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_design_A11_wrapper_0_0 || ORIG_REF_NAME==design_main_project_design_A11_wrapper_0_0}]

# IP: bd/design_main_project/ip/design_main_project_design_A01_wrapper_0_0/design_main_project_design_A01_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_design_A01_wrapper_0_0 || ORIG_REF_NAME==design_main_project_design_A01_wrapper_0_0}]

# IP: bd/design_main_project/ip/design_main_project_xup_2_to_1_mux_vector_0_0/design_main_project_xup_2_to_1_mux_vector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xup_2_to_1_mux_vector_0_0 || ORIG_REF_NAME==design_main_project_xup_2_to_1_mux_vector_0_0}]

# IP: bd/design_main_project/ip/design_main_project_xup_2_to_1_mux_vector_0_1/design_main_project_xup_2_to_1_mux_vector_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xup_2_to_1_mux_vector_0_1 || ORIG_REF_NAME==design_main_project_xup_2_to_1_mux_vector_0_1}]

# IP: bd/design_main_project/ip/design_main_project_xlconcat_0_0/design_main_project_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xlconcat_0_0 || ORIG_REF_NAME==design_main_project_xlconcat_0_0}]

# IP: bd/design_main_project/ip/design_main_project_xlconstant_0_0/design_main_project_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xlconstant_0_0 || ORIG_REF_NAME==design_main_project_xlconstant_0_0}]

# IP: bd/design_main_project/ip/design_main_project_xlconstant_0_1/design_main_project_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xlconstant_0_1 || ORIG_REF_NAME==design_main_project_xlconstant_0_1}]

# IP: bd/design_main_project/ip/design_main_project_xup_or3_0_0/design_main_project_xup_or3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xup_or3_0_0 || ORIG_REF_NAME==design_main_project_xup_or3_0_0}]

# IP: bd/design_main_project/ip/design_main_project_xlconcat_0_1/design_main_project_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xlconcat_0_1 || ORIG_REF_NAME==design_main_project_xlconcat_0_1}]

# IP: bd/design_main_project/ip/design_main_project_xlconcat_0_2/design_main_project_xlconcat_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xlconcat_0_2 || ORIG_REF_NAME==design_main_project_xlconcat_0_2}]

# IP: bd/design_main_project/ip/design_main_project_xlconstant_1_0/design_main_project_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xlconstant_1_0 || ORIG_REF_NAME==design_main_project_xlconstant_1_0}]

# IP: bd/design_main_project/ip/design_main_project_xlconstant_3_0/design_main_project_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xlconstant_3_0 || ORIG_REF_NAME==design_main_project_xlconstant_3_0}]

# IP: bd/design_main_project/ip/design_main_project_xup_or3_1_0/design_main_project_xup_or3_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xup_or3_1_0 || ORIG_REF_NAME==design_main_project_xup_or3_1_0}]

# IP: bd/design_main_project/ip/design_main_project_xup_or2_0_0/design_main_project_xup_or2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xup_or2_0_0 || ORIG_REF_NAME==design_main_project_xup_or2_0_0}]

# IP: bd/design_main_project/ip/design_main_project_xup_or2_1_0/design_main_project_xup_or2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xup_or2_1_0 || ORIG_REF_NAME==design_main_project_xup_or2_1_0}]

# IP: bd/design_main_project/ip/design_main_project_counters_0_1/design_main_project_counters_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_counters_0_1 || ORIG_REF_NAME==design_main_project_counters_0_1}]

# IP: bd/design_main_project/ip/design_main_project_counters_0_0/design_main_project_counters_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_counters_0_0 || ORIG_REF_NAME==design_main_project_counters_0_0}]

# IP: bd/design_main_project/ip/design_main_project_xup_or2_2_0/design_main_project_xup_or2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xup_or2_2_0 || ORIG_REF_NAME==design_main_project_xup_or2_2_0}]

# IP: bd/design_main_project/ip/design_main_project_counters_0_2/design_main_project_counters_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_counters_0_2 || ORIG_REF_NAME==design_main_project_counters_0_2}]

# IP: bd/design_main_project/ip/design_main_project_xup_or2_LR2_0/design_main_project_xup_or2_LR2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xup_or2_LR2_0 || ORIG_REF_NAME==design_main_project_xup_or2_LR2_0}]

# IP: bd/design_main_project/ip/design_main_project_xlconcat_0_3/design_main_project_xlconcat_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xlconcat_0_3 || ORIG_REF_NAME==design_main_project_xlconcat_0_3}]

# IP: bd/design_main_project/ip/design_main_project_seg7display_0_0/design_main_project_seg7display_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_seg7display_0_0 || ORIG_REF_NAME==design_main_project_seg7display_0_0}]

# IP: bd/design_main_project/ip/design_main_project_xup_and2_0_0/design_main_project_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xup_and2_0_0 || ORIG_REF_NAME==design_main_project_xup_and2_0_0}]

# IP: bd/design_main_project/ip/design_main_project_xup_inv_0_0/design_main_project_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xup_inv_0_0 || ORIG_REF_NAME==design_main_project_xup_inv_0_0}]

# IP: bd/design_main_project/ip/design_main_project_xup_inv_1_0/design_main_project_xup_inv_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xup_inv_1_0 || ORIG_REF_NAME==design_main_project_xup_inv_1_0}]

# IP: bd/design_main_project/ip/design_main_project_xup_and2_1_0/design_main_project_xup_and2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xup_and2_1_0 || ORIG_REF_NAME==design_main_project_xup_and2_1_0}]

# IP: bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/design_main_project_design_yeni_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_design_yeni_wrapper_0_0 || ORIG_REF_NAME==design_main_project_design_yeni_wrapper_0_0}]

# IP: bd/design_main_project/ip/design_main_project_xup_or5_0_0/design_main_project_xup_or5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xup_or5_0_0 || ORIG_REF_NAME==design_main_project_xup_or5_0_0}]

# IP: bd/design_main_project/ip/design_main_project_xup_or4_0_0/design_main_project_xup_or4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xup_or4_0_0 || ORIG_REF_NAME==design_main_project_xup_or4_0_0}]

# IP: bd/design_main_project/ip/design_main_project_xup_or5_1_0/design_main_project_xup_or5_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xup_or5_1_0 || ORIG_REF_NAME==design_main_project_xup_or5_1_0}]

# IP: bd/design_main_project/ip/design_main_project_xup_and2_2_0/design_main_project_xup_and2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xup_and2_2_0 || ORIG_REF_NAME==design_main_project_xup_and2_2_0}]

# IP: bd/design_main_project/ip/design_main_project_xup_or4_1_0/design_main_project_xup_or4_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xup_or4_1_0 || ORIG_REF_NAME==design_main_project_xup_or4_1_0}]

# IP: bd/design_main_project/ip/design_main_project_xup_and2_2_1/design_main_project_xup_and2_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_main_project_xup_and2_2_1 || ORIG_REF_NAME==design_main_project_xup_and2_2_1}]

# XDC: bd/design_main_project/design_main_project_ooc.xdc
