# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/design_main_project_design_A11_wrapper_0_0.xci
# IP: The module: 'design_main_project_design_A11_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/ip/design_A11_xup_inv_0_0/design_A11_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A11_xup_inv_0_0 || ORIG_REF_NAME==design_A11_xup_inv_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/ip/design_A11_xup_inv_0_1/design_A11_xup_inv_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A11_xup_inv_0_1 || ORIG_REF_NAME==design_A11_xup_inv_0_1}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/ip/design_A11_xup_inv_0_2/design_A11_xup_inv_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A11_xup_inv_0_2 || ORIG_REF_NAME==design_A11_xup_inv_0_2}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/ip/design_A11_xup_and4_0_0/design_A11_xup_and4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A11_xup_and4_0_0 || ORIG_REF_NAME==design_A11_xup_and4_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/ip/design_A11_xup_and4_0_1/design_A11_xup_and4_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A11_xup_and4_0_1 || ORIG_REF_NAME==design_A11_xup_and4_0_1}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/ip/design_A11_xup_and4_0_2/design_A11_xup_and4_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A11_xup_and4_0_2 || ORIG_REF_NAME==design_A11_xup_and4_0_2}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/ip/design_A11_xup_and4_0_3/design_A11_xup_and4_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A11_xup_and4_0_3 || ORIG_REF_NAME==design_A11_xup_and4_0_3}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/ip/design_A11_xup_and4_0_4/design_A11_xup_and4_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A11_xup_and4_0_4 || ORIG_REF_NAME==design_A11_xup_and4_0_4}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/ip/design_A11_xup_and4_0_5/design_A11_xup_and4_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A11_xup_and4_0_5 || ORIG_REF_NAME==design_A11_xup_and4_0_5}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/ip/design_A11_xup_or5_0_0/design_A11_xup_or5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A11_xup_or5_0_0 || ORIG_REF_NAME==design_A11_xup_or5_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/ip/design_A11_xup_or2_0_0/design_A11_xup_or2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A11_xup_or2_0_0 || ORIG_REF_NAME==design_A11_xup_or2_0_0}]

# XDC: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/design_A11_ooc.xdc

# IP: C:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/design_main_project_design_A11_wrapper_0_0.xci
# IP: The module: 'design_main_project_design_A11_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/ip/design_A11_xup_inv_0_0/design_A11_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A11_xup_inv_0_0 || ORIG_REF_NAME==design_A11_xup_inv_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/ip/design_A11_xup_inv_0_1/design_A11_xup_inv_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A11_xup_inv_0_1 || ORIG_REF_NAME==design_A11_xup_inv_0_1}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/ip/design_A11_xup_inv_0_2/design_A11_xup_inv_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A11_xup_inv_0_2 || ORIG_REF_NAME==design_A11_xup_inv_0_2}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/ip/design_A11_xup_and4_0_0/design_A11_xup_and4_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A11_xup_and4_0_0 || ORIG_REF_NAME==design_A11_xup_and4_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/ip/design_A11_xup_and4_0_1/design_A11_xup_and4_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A11_xup_and4_0_1 || ORIG_REF_NAME==design_A11_xup_and4_0_1}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/ip/design_A11_xup_and4_0_2/design_A11_xup_and4_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A11_xup_and4_0_2 || ORIG_REF_NAME==design_A11_xup_and4_0_2}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/ip/design_A11_xup_and4_0_3/design_A11_xup_and4_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A11_xup_and4_0_3 || ORIG_REF_NAME==design_A11_xup_and4_0_3}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/ip/design_A11_xup_and4_0_4/design_A11_xup_and4_0_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A11_xup_and4_0_4 || ORIG_REF_NAME==design_A11_xup_and4_0_4}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/ip/design_A11_xup_and4_0_5/design_A11_xup_and4_0_5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A11_xup_and4_0_5 || ORIG_REF_NAME==design_A11_xup_and4_0_5}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/ip/design_A11_xup_or5_0_0/design_A11_xup_or5_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A11_xup_or5_0_0 || ORIG_REF_NAME==design_A11_xup_or5_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/ip/design_A11_xup_or2_0_0/design_A11_xup_or2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A11_xup_or2_0_0 || ORIG_REF_NAME==design_A11_xup_or2_0_0}]

# XDC: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A11_wrapper_0_0/bd/design_A11/design_A11_ooc.xdc
