# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_debouncer_wrapper_0_2/design_main_project_design_debouncer_wrapper_0_2.xci
# IP: The module: 'design_main_project_design_debouncer_wrapper_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_debouncer_wrapper_0_2/bd/design_debouncer/ip/design_debouncer_xup_dff_en_reset_0_0/design_debouncer_xup_dff_en_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_debouncer_xup_dff_en_reset_0_0 || ORIG_REF_NAME==design_debouncer_xup_dff_en_reset_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_debouncer_wrapper_0_2/bd/design_debouncer/ip/design_debouncer_xup_dff_0_0/design_debouncer_xup_dff_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_debouncer_xup_dff_0_0 || ORIG_REF_NAME==design_debouncer_xup_dff_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_debouncer_wrapper_0_2/bd/design_debouncer/ip/design_debouncer_xup_or2_0_0/design_debouncer_xup_or2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_debouncer_xup_or2_0_0 || ORIG_REF_NAME==design_debouncer_xup_or2_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_debouncer_wrapper_0_2/bd/design_debouncer/ip/design_debouncer_xup_dff_0_1/design_debouncer_xup_dff_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_debouncer_xup_dff_0_1 || ORIG_REF_NAME==design_debouncer_xup_dff_0_1}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_debouncer_wrapper_0_2/bd/design_debouncer/ip/design_debouncer_xup_xor2_0_0/design_debouncer_xup_xor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_debouncer_xup_xor2_0_0 || ORIG_REF_NAME==design_debouncer_xup_xor2_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_debouncer_wrapper_0_2/bd/design_debouncer/ip/design_debouncer_xup_xor2_0_1/design_debouncer_xup_xor2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_debouncer_xup_xor2_0_1 || ORIG_REF_NAME==design_debouncer_xup_xor2_0_1}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_debouncer_wrapper_0_2/bd/design_debouncer/ip/design_debouncer_xlconstant_0_0/design_debouncer_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_debouncer_xlconstant_0_0 || ORIG_REF_NAME==design_debouncer_xlconstant_0_0}]

# XDC: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_debouncer_wrapper_0_2/bd/design_debouncer/design_debouncer_ooc.xdc

# IP: C:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_debouncer_wrapper_0_2/design_main_project_design_debouncer_wrapper_0_2.xci
# IP: The module: 'design_main_project_design_debouncer_wrapper_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_debouncer_wrapper_0_2/bd/design_debouncer/ip/design_debouncer_xup_dff_en_reset_0_0/design_debouncer_xup_dff_en_reset_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_debouncer_xup_dff_en_reset_0_0 || ORIG_REF_NAME==design_debouncer_xup_dff_en_reset_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_debouncer_wrapper_0_2/bd/design_debouncer/ip/design_debouncer_xup_dff_0_0/design_debouncer_xup_dff_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_debouncer_xup_dff_0_0 || ORIG_REF_NAME==design_debouncer_xup_dff_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_debouncer_wrapper_0_2/bd/design_debouncer/ip/design_debouncer_xup_or2_0_0/design_debouncer_xup_or2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_debouncer_xup_or2_0_0 || ORIG_REF_NAME==design_debouncer_xup_or2_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_debouncer_wrapper_0_2/bd/design_debouncer/ip/design_debouncer_xup_dff_0_1/design_debouncer_xup_dff_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_debouncer_xup_dff_0_1 || ORIG_REF_NAME==design_debouncer_xup_dff_0_1}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_debouncer_wrapper_0_2/bd/design_debouncer/ip/design_debouncer_xup_xor2_0_0/design_debouncer_xup_xor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_debouncer_xup_xor2_0_0 || ORIG_REF_NAME==design_debouncer_xup_xor2_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_debouncer_wrapper_0_2/bd/design_debouncer/ip/design_debouncer_xup_xor2_0_1/design_debouncer_xup_xor2_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_debouncer_xup_xor2_0_1 || ORIG_REF_NAME==design_debouncer_xup_xor2_0_1}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_debouncer_wrapper_0_2/bd/design_debouncer/ip/design_debouncer_xlconstant_0_0/design_debouncer_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_debouncer_xlconstant_0_0 || ORIG_REF_NAME==design_debouncer_xlconstant_0_0}]

# XDC: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_debouncer_wrapper_0_2/bd/design_debouncer/design_debouncer_ooc.xdc
