# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/design_main_project_design_yeni_wrapper_0_0.xci
# IP: The module: 'design_main_project_design_yeni_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_inv_0_0/design_yeni_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_inv_0_0 || ORIG_REF_NAME==design_yeni_xup_inv_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_inv_0_1/design_yeni_xup_inv_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_inv_0_1 || ORIG_REF_NAME==design_yeni_xup_inv_0_1}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_inv_0_2/design_yeni_xup_inv_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_inv_0_2 || ORIG_REF_NAME==design_yeni_xup_inv_0_2}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_and4_0_0/design_yeni_xup_and4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_and4_0_0 || ORIG_REF_NAME==design_yeni_xup_and4_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_and4_0_1/design_yeni_xup_and4_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_and4_0_1 || ORIG_REF_NAME==design_yeni_xup_and4_0_1}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_and4_1_0/design_yeni_xup_and4_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_and4_1_0 || ORIG_REF_NAME==design_yeni_xup_and4_1_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_and4_1_1/design_yeni_xup_and4_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_and4_1_1 || ORIG_REF_NAME==design_yeni_xup_and4_1_1}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_and4_1_2/design_yeni_xup_and4_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_and4_1_2 || ORIG_REF_NAME==design_yeni_xup_and4_1_2}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_and4_1_3/design_yeni_xup_and4_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_and4_1_3 || ORIG_REF_NAME==design_yeni_xup_and4_1_3}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_and4_1_4/design_yeni_xup_and4_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_and4_1_4 || ORIG_REF_NAME==design_yeni_xup_and4_1_4}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_and4_1_5/design_yeni_xup_and4_1_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_and4_1_5 || ORIG_REF_NAME==design_yeni_xup_and4_1_5}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_and4_1_6/design_yeni_xup_and4_1_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_and4_1_6 || ORIG_REF_NAME==design_yeni_xup_and4_1_6}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_or4_0_0/design_yeni_xup_or4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_or4_0_0 || ORIG_REF_NAME==design_yeni_xup_or4_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_or5_0_0/design_yeni_xup_or5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_or5_0_0 || ORIG_REF_NAME==design_yeni_xup_or5_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_or2_0_0/design_yeni_xup_or2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_or2_0_0 || ORIG_REF_NAME==design_yeni_xup_or2_0_0}]

# XDC: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/design_yeni_ooc.xdc

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/design_main_project_design_yeni_wrapper_0_0.xci
# IP: The module: 'design_main_project_design_yeni_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_inv_0_0/design_yeni_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_inv_0_0 || ORIG_REF_NAME==design_yeni_xup_inv_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_inv_0_1/design_yeni_xup_inv_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_inv_0_1 || ORIG_REF_NAME==design_yeni_xup_inv_0_1}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_inv_0_2/design_yeni_xup_inv_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_inv_0_2 || ORIG_REF_NAME==design_yeni_xup_inv_0_2}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_and4_0_0/design_yeni_xup_and4_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_and4_0_0 || ORIG_REF_NAME==design_yeni_xup_and4_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_and4_0_1/design_yeni_xup_and4_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_and4_0_1 || ORIG_REF_NAME==design_yeni_xup_and4_0_1}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_and4_1_0/design_yeni_xup_and4_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_and4_1_0 || ORIG_REF_NAME==design_yeni_xup_and4_1_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_and4_1_1/design_yeni_xup_and4_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_and4_1_1 || ORIG_REF_NAME==design_yeni_xup_and4_1_1}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_and4_1_2/design_yeni_xup_and4_1_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_and4_1_2 || ORIG_REF_NAME==design_yeni_xup_and4_1_2}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_and4_1_3/design_yeni_xup_and4_1_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_and4_1_3 || ORIG_REF_NAME==design_yeni_xup_and4_1_3}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_and4_1_4/design_yeni_xup_and4_1_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_and4_1_4 || ORIG_REF_NAME==design_yeni_xup_and4_1_4}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_and4_1_5/design_yeni_xup_and4_1_5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_and4_1_5 || ORIG_REF_NAME==design_yeni_xup_and4_1_5}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_and4_1_6/design_yeni_xup_and4_1_6.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_and4_1_6 || ORIG_REF_NAME==design_yeni_xup_and4_1_6}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_or4_0_0/design_yeni_xup_or4_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_or4_0_0 || ORIG_REF_NAME==design_yeni_xup_or4_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_or5_0_0/design_yeni_xup_or5_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_or5_0_0 || ORIG_REF_NAME==design_yeni_xup_or5_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/ip/design_yeni_xup_or2_0_0/design_yeni_xup_or2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_yeni_xup_or2_0_0 || ORIG_REF_NAME==design_yeni_xup_or2_0_0}]

# XDC: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_yeni_wrapper_0_0/bd/design_yeni/design_yeni_ooc.xdc
