# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A01_wrapper_0_0/design_main_project_design_A01_wrapper_0_0.xci
# IP: The module: 'design_main_project_design_A01_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A01_wrapper_0_0/bd/design_A01/ip/design_A01_xup_inv_0_0/design_A01_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A01_xup_inv_0_0 || ORIG_REF_NAME==design_A01_xup_inv_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A01_wrapper_0_0/bd/design_A01/ip/design_A01_xup_inv_0_1/design_A01_xup_inv_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A01_xup_inv_0_1 || ORIG_REF_NAME==design_A01_xup_inv_0_1}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A01_wrapper_0_0/bd/design_A01/ip/design_A01_xup_inv_0_2/design_A01_xup_inv_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A01_xup_inv_0_2 || ORIG_REF_NAME==design_A01_xup_inv_0_2}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A01_wrapper_0_0/bd/design_A01/ip/design_A01_xup_and4_0_0/design_A01_xup_and4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A01_xup_and4_0_0 || ORIG_REF_NAME==design_A01_xup_and4_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A01_wrapper_0_0/bd/design_A01/ip/design_A01_xup_and4_0_1/design_A01_xup_and4_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A01_xup_and4_0_1 || ORIG_REF_NAME==design_A01_xup_and4_0_1}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A01_wrapper_0_0/bd/design_A01/ip/design_A01_xup_and4_0_2/design_A01_xup_and4_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A01_xup_and4_0_2 || ORIG_REF_NAME==design_A01_xup_and4_0_2}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A01_wrapper_0_0/bd/design_A01/ip/design_A01_xup_or3_0_0/design_A01_xup_or3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A01_xup_or3_0_0 || ORIG_REF_NAME==design_A01_xup_or3_0_0}]

# XDC: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A01_wrapper_0_0/bd/design_A01/design_A01_ooc.xdc

# IP: C:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A01_wrapper_0_0/design_main_project_design_A01_wrapper_0_0.xci
# IP: The module: 'design_main_project_design_A01_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A01_wrapper_0_0/bd/design_A01/ip/design_A01_xup_inv_0_0/design_A01_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A01_xup_inv_0_0 || ORIG_REF_NAME==design_A01_xup_inv_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A01_wrapper_0_0/bd/design_A01/ip/design_A01_xup_inv_0_1/design_A01_xup_inv_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A01_xup_inv_0_1 || ORIG_REF_NAME==design_A01_xup_inv_0_1}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A01_wrapper_0_0/bd/design_A01/ip/design_A01_xup_inv_0_2/design_A01_xup_inv_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A01_xup_inv_0_2 || ORIG_REF_NAME==design_A01_xup_inv_0_2}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A01_wrapper_0_0/bd/design_A01/ip/design_A01_xup_and4_0_0/design_A01_xup_and4_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A01_xup_and4_0_0 || ORIG_REF_NAME==design_A01_xup_and4_0_0}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A01_wrapper_0_0/bd/design_A01/ip/design_A01_xup_and4_0_1/design_A01_xup_and4_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A01_xup_and4_0_1 || ORIG_REF_NAME==design_A01_xup_and4_0_1}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A01_wrapper_0_0/bd/design_A01/ip/design_A01_xup_and4_0_2/design_A01_xup_and4_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A01_xup_and4_0_2 || ORIG_REF_NAME==design_A01_xup_and4_0_2}]

# IP: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A01_wrapper_0_0/bd/design_A01/ip/design_A01_xup_or3_0_0/design_A01_xup_or3_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_A01_xup_or3_0_0 || ORIG_REF_NAME==design_A01_xup_or3_0_0}]

# XDC: c:/Users/life/project_1/project_1.srcs/sources_1/bd/design_main_project/ip/design_main_project_design_A01_wrapper_0_0/bd/design_A01/design_A01_ooc.xdc
